Aug 28 00:23:33 ubuntu-s-1vcpu-1gb-sgp1-01 python3[116063]: === UAFT tg_runner started ===
Aug 28 00:38:52 ubuntu-s-1vcpu-1gb-sgp1-01 python3[116474]: === UAFT tg_runner started ===
Aug 28 00:42:50 ubuntu-s-1vcpu-1gb-sgp1-01 python3[116523]: === UAFT tg_runner started ===
Aug 28 01:11:28 ubuntu-s-1vcpu-1gb-sgp1-01 python3[116523]: Traceback (most recent call last):
Aug 28 01:11:28 ubuntu-s-1vcpu-1gb-sgp1-01 python3[116523]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 43, in main
Aug 28 01:11:28 ubuntu-s-1vcpu-1gb-sgp1-01 python3[116523]:     resp.raise_for_status()
Aug 28 01:11:28 ubuntu-s-1vcpu-1gb-sgp1-01 python3[116523]:   File "/home/uaft/.local/lib/python3.10/site-packages/requests/models.py", line 1026, in raise_for_status
Aug 28 01:11:28 ubuntu-s-1vcpu-1gb-sgp1-01 python3[116523]:     raise HTTPError(http_error_msg, response=self)
Aug 28 01:11:28 ubuntu-s-1vcpu-1gb-sgp1-01 python3[116523]: requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://api.telegram.org/bot8075960342:AAElNMpncauiSVyWXYLTOB45BqCiBVLBmuc/getUpdates?timeout=25&offset=131648150
