Aug 29 15:33:29 ubuntu-s-1vcpu-1gb-sgp1-01 python[184861]: === UAFT tg_runner started ===
Aug 29 15:33:48 ubuntu-s-1vcpu-1gb-sgp1-01 python[184861]: Traceback (most recent call last):
Aug 29 15:33:48 ubuntu-s-1vcpu-1gb-sgp1-01 python[184861]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 60, in main
Aug 29 15:33:48 ubuntu-s-1vcpu-1gb-sgp1-01 python[184861]:     res = AI.route(event)  # ожидаем dict
Aug 29 15:33:48 ubuntu-s-1vcpu-1gb-sgp1-01 python[184861]: AttributeError: module 'ai_supervisor' has no attribute 'route'
Aug 29 15:34:01 ubuntu-s-1vcpu-1gb-sgp1-01 python[184861]: Traceback (most recent call last):
Aug 29 15:34:01 ubuntu-s-1vcpu-1gb-sgp1-01 python[184861]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 60, in main
Aug 29 15:34:01 ubuntu-s-1vcpu-1gb-sgp1-01 python[184861]:     res = AI.route(event)  # ожидаем dict
Aug 29 15:34:01 ubuntu-s-1vcpu-1gb-sgp1-01 python[184861]: AttributeError: module 'ai_supervisor' has no attribute 'route'
Aug 29 15:34:07 ubuntu-s-1vcpu-1gb-sgp1-01 python[184861]: Traceback (most recent call last):
Aug 29 15:34:07 ubuntu-s-1vcpu-1gb-sgp1-01 python[184861]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 60, in main
Aug 29 15:34:07 ubuntu-s-1vcpu-1gb-sgp1-01 python[184861]:     res = AI.route(event)  # ожидаем dict
Aug 29 15:34:07 ubuntu-s-1vcpu-1gb-sgp1-01 python[184861]: AttributeError: module 'ai_supervisor' has no attribute 'route'
