Aug 30 17:42:00 ubuntu-s-1vcpu-1gb-sgp1-01 python[286526]: Traceback (most recent call last):
Aug 30 17:42:00 ubuntu-s-1vcpu-1gb-sgp1-01 python[286526]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 60, in main
Aug 30 17:42:00 ubuntu-s-1vcpu-1gb-sgp1-01 python[286526]:     res = AI.route(event)  # ожидаем dict
Aug 30 17:42:00 ubuntu-s-1vcpu-1gb-sgp1-01 python[286526]: AttributeError: module 'ai_supervisor' has no attribute 'route'
