Aug 30 20:55:02 ubuntu-s-1vcpu-1gb-sgp1-01 python[301253]: Traceback (most recent call last):
Aug 30 20:55:02 ubuntu-s-1vcpu-1gb-sgp1-01 python[301253]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:55:02 ubuntu-s-1vcpu-1gb-sgp1-01 python[301253]:     bot = Bot(token=TOKEN)
Aug 30 20:55:02 ubuntu-s-1vcpu-1gb-sgp1-01 python[301253]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:55:02 ubuntu-s-1vcpu-1gb-sgp1-01 python[301253]:     api.check_token(token)
Aug 30 20:55:02 ubuntu-s-1vcpu-1gb-sgp1-01 python[301253]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:55:02 ubuntu-s-1vcpu-1gb-sgp1-01 python[301253]:     raise exceptions.ValidationError(message)
Aug 30 20:55:02 ubuntu-s-1vcpu-1gb-sgp1-01 python[301253]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:55:05 ubuntu-s-1vcpu-1gb-sgp1-01 python[301263]: Traceback (most recent call last):
Aug 30 20:55:05 ubuntu-s-1vcpu-1gb-sgp1-01 python[301263]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:55:05 ubuntu-s-1vcpu-1gb-sgp1-01 python[301263]:     bot = Bot(token=TOKEN)
Aug 30 20:55:05 ubuntu-s-1vcpu-1gb-sgp1-01 python[301263]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:55:05 ubuntu-s-1vcpu-1gb-sgp1-01 python[301263]:     api.check_token(token)
Aug 30 20:55:05 ubuntu-s-1vcpu-1gb-sgp1-01 python[301263]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:55:05 ubuntu-s-1vcpu-1gb-sgp1-01 python[301263]:     raise exceptions.ValidationError(message)
Aug 30 20:55:05 ubuntu-s-1vcpu-1gb-sgp1-01 python[301263]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:55:08 ubuntu-s-1vcpu-1gb-sgp1-01 python[301266]: Traceback (most recent call last):
Aug 30 20:55:08 ubuntu-s-1vcpu-1gb-sgp1-01 python[301266]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:55:08 ubuntu-s-1vcpu-1gb-sgp1-01 python[301266]:     bot = Bot(token=TOKEN)
Aug 30 20:55:08 ubuntu-s-1vcpu-1gb-sgp1-01 python[301266]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:55:08 ubuntu-s-1vcpu-1gb-sgp1-01 python[301266]:     api.check_token(token)
Aug 30 20:55:08 ubuntu-s-1vcpu-1gb-sgp1-01 python[301266]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:55:08 ubuntu-s-1vcpu-1gb-sgp1-01 python[301266]:     raise exceptions.ValidationError(message)
Aug 30 20:55:08 ubuntu-s-1vcpu-1gb-sgp1-01 python[301266]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:55:10 ubuntu-s-1vcpu-1gb-sgp1-01 python[301271]: Traceback (most recent call last):
Aug 30 20:55:10 ubuntu-s-1vcpu-1gb-sgp1-01 python[301271]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:55:10 ubuntu-s-1vcpu-1gb-sgp1-01 python[301271]:     bot = Bot(token=TOKEN)
Aug 30 20:55:10 ubuntu-s-1vcpu-1gb-sgp1-01 python[301271]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:55:10 ubuntu-s-1vcpu-1gb-sgp1-01 python[301271]:     api.check_token(token)
Aug 30 20:55:10 ubuntu-s-1vcpu-1gb-sgp1-01 python[301271]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:55:10 ubuntu-s-1vcpu-1gb-sgp1-01 python[301271]:     raise exceptions.ValidationError(message)
Aug 30 20:55:10 ubuntu-s-1vcpu-1gb-sgp1-01 python[301271]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:55:13 ubuntu-s-1vcpu-1gb-sgp1-01 python[301279]: Traceback (most recent call last):
Aug 30 20:55:13 ubuntu-s-1vcpu-1gb-sgp1-01 python[301279]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:55:13 ubuntu-s-1vcpu-1gb-sgp1-01 python[301279]:     bot = Bot(token=TOKEN)
Aug 30 20:55:13 ubuntu-s-1vcpu-1gb-sgp1-01 python[301279]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:55:13 ubuntu-s-1vcpu-1gb-sgp1-01 python[301279]:     api.check_token(token)
Aug 30 20:55:13 ubuntu-s-1vcpu-1gb-sgp1-01 python[301279]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:55:13 ubuntu-s-1vcpu-1gb-sgp1-01 python[301279]:     raise exceptions.ValidationError(message)
Aug 30 20:55:13 ubuntu-s-1vcpu-1gb-sgp1-01 python[301279]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:55:15 ubuntu-s-1vcpu-1gb-sgp1-01 python[301280]: Traceback (most recent call last):
Aug 30 20:55:15 ubuntu-s-1vcpu-1gb-sgp1-01 python[301280]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:55:15 ubuntu-s-1vcpu-1gb-sgp1-01 python[301280]:     bot = Bot(token=TOKEN)
Aug 30 20:55:15 ubuntu-s-1vcpu-1gb-sgp1-01 python[301280]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:55:15 ubuntu-s-1vcpu-1gb-sgp1-01 python[301280]:     api.check_token(token)
Aug 30 20:55:15 ubuntu-s-1vcpu-1gb-sgp1-01 python[301280]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:55:15 ubuntu-s-1vcpu-1gb-sgp1-01 python[301280]:     raise exceptions.ValidationError(message)
Aug 30 20:55:15 ubuntu-s-1vcpu-1gb-sgp1-01 python[301280]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:55:18 ubuntu-s-1vcpu-1gb-sgp1-01 python[301282]: Traceback (most recent call last):
Aug 30 20:55:18 ubuntu-s-1vcpu-1gb-sgp1-01 python[301282]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:55:18 ubuntu-s-1vcpu-1gb-sgp1-01 python[301282]:     bot = Bot(token=TOKEN)
Aug 30 20:55:18 ubuntu-s-1vcpu-1gb-sgp1-01 python[301282]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:55:18 ubuntu-s-1vcpu-1gb-sgp1-01 python[301282]:     api.check_token(token)
Aug 30 20:55:18 ubuntu-s-1vcpu-1gb-sgp1-01 python[301282]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:55:18 ubuntu-s-1vcpu-1gb-sgp1-01 python[301282]:     raise exceptions.ValidationError(message)
Aug 30 20:55:18 ubuntu-s-1vcpu-1gb-sgp1-01 python[301282]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:55:21 ubuntu-s-1vcpu-1gb-sgp1-01 python[301286]: Traceback (most recent call last):
Aug 30 20:55:21 ubuntu-s-1vcpu-1gb-sgp1-01 python[301286]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:55:21 ubuntu-s-1vcpu-1gb-sgp1-01 python[301286]:     bot = Bot(token=TOKEN)
Aug 30 20:55:21 ubuntu-s-1vcpu-1gb-sgp1-01 python[301286]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:55:21 ubuntu-s-1vcpu-1gb-sgp1-01 python[301286]:     api.check_token(token)
Aug 30 20:55:21 ubuntu-s-1vcpu-1gb-sgp1-01 python[301286]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:55:21 ubuntu-s-1vcpu-1gb-sgp1-01 python[301286]:     raise exceptions.ValidationError(message)
Aug 30 20:55:21 ubuntu-s-1vcpu-1gb-sgp1-01 python[301286]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:55:23 ubuntu-s-1vcpu-1gb-sgp1-01 python[301288]: Traceback (most recent call last):
Aug 30 20:55:23 ubuntu-s-1vcpu-1gb-sgp1-01 python[301288]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:55:23 ubuntu-s-1vcpu-1gb-sgp1-01 python[301288]:     bot = Bot(token=TOKEN)
Aug 30 20:55:23 ubuntu-s-1vcpu-1gb-sgp1-01 python[301288]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:55:23 ubuntu-s-1vcpu-1gb-sgp1-01 python[301288]:     api.check_token(token)
Aug 30 20:55:23 ubuntu-s-1vcpu-1gb-sgp1-01 python[301288]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:55:23 ubuntu-s-1vcpu-1gb-sgp1-01 python[301288]:     raise exceptions.ValidationError(message)
Aug 30 20:55:23 ubuntu-s-1vcpu-1gb-sgp1-01 python[301288]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:55:26 ubuntu-s-1vcpu-1gb-sgp1-01 python[301291]: Traceback (most recent call last):
Aug 30 20:55:26 ubuntu-s-1vcpu-1gb-sgp1-01 python[301291]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:55:26 ubuntu-s-1vcpu-1gb-sgp1-01 python[301291]:     bot = Bot(token=TOKEN)
Aug 30 20:55:26 ubuntu-s-1vcpu-1gb-sgp1-01 python[301291]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:55:26 ubuntu-s-1vcpu-1gb-sgp1-01 python[301291]:     api.check_token(token)
Aug 30 20:55:26 ubuntu-s-1vcpu-1gb-sgp1-01 python[301291]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:55:26 ubuntu-s-1vcpu-1gb-sgp1-01 python[301291]:     raise exceptions.ValidationError(message)
Aug 30 20:55:26 ubuntu-s-1vcpu-1gb-sgp1-01 python[301291]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:55:28 ubuntu-s-1vcpu-1gb-sgp1-01 python[301296]: Traceback (most recent call last):
Aug 30 20:55:28 ubuntu-s-1vcpu-1gb-sgp1-01 python[301296]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:55:28 ubuntu-s-1vcpu-1gb-sgp1-01 python[301296]:     bot = Bot(token=TOKEN)
Aug 30 20:55:28 ubuntu-s-1vcpu-1gb-sgp1-01 python[301296]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:55:28 ubuntu-s-1vcpu-1gb-sgp1-01 python[301296]:     api.check_token(token)
Aug 30 20:55:28 ubuntu-s-1vcpu-1gb-sgp1-01 python[301296]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:55:28 ubuntu-s-1vcpu-1gb-sgp1-01 python[301296]:     raise exceptions.ValidationError(message)
Aug 30 20:55:28 ubuntu-s-1vcpu-1gb-sgp1-01 python[301296]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:55:31 ubuntu-s-1vcpu-1gb-sgp1-01 python[301300]: Traceback (most recent call last):
Aug 30 20:55:31 ubuntu-s-1vcpu-1gb-sgp1-01 python[301300]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:55:31 ubuntu-s-1vcpu-1gb-sgp1-01 python[301300]:     bot = Bot(token=TOKEN)
Aug 30 20:55:31 ubuntu-s-1vcpu-1gb-sgp1-01 python[301300]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:55:31 ubuntu-s-1vcpu-1gb-sgp1-01 python[301300]:     api.check_token(token)
Aug 30 20:55:31 ubuntu-s-1vcpu-1gb-sgp1-01 python[301300]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:55:31 ubuntu-s-1vcpu-1gb-sgp1-01 python[301300]:     raise exceptions.ValidationError(message)
Aug 30 20:55:31 ubuntu-s-1vcpu-1gb-sgp1-01 python[301300]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:55:34 ubuntu-s-1vcpu-1gb-sgp1-01 python[301302]: Traceback (most recent call last):
Aug 30 20:55:34 ubuntu-s-1vcpu-1gb-sgp1-01 python[301302]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:55:34 ubuntu-s-1vcpu-1gb-sgp1-01 python[301302]:     bot = Bot(token=TOKEN)
Aug 30 20:55:34 ubuntu-s-1vcpu-1gb-sgp1-01 python[301302]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:55:34 ubuntu-s-1vcpu-1gb-sgp1-01 python[301302]:     api.check_token(token)
Aug 30 20:55:34 ubuntu-s-1vcpu-1gb-sgp1-01 python[301302]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:55:34 ubuntu-s-1vcpu-1gb-sgp1-01 python[301302]:     raise exceptions.ValidationError(message)
Aug 30 20:55:34 ubuntu-s-1vcpu-1gb-sgp1-01 python[301302]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:55:36 ubuntu-s-1vcpu-1gb-sgp1-01 python[301306]: Traceback (most recent call last):
Aug 30 20:55:36 ubuntu-s-1vcpu-1gb-sgp1-01 python[301306]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:55:36 ubuntu-s-1vcpu-1gb-sgp1-01 python[301306]:     bot = Bot(token=TOKEN)
Aug 30 20:55:36 ubuntu-s-1vcpu-1gb-sgp1-01 python[301306]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:55:36 ubuntu-s-1vcpu-1gb-sgp1-01 python[301306]:     api.check_token(token)
Aug 30 20:55:36 ubuntu-s-1vcpu-1gb-sgp1-01 python[301306]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:55:36 ubuntu-s-1vcpu-1gb-sgp1-01 python[301306]:     raise exceptions.ValidationError(message)
Aug 30 20:55:36 ubuntu-s-1vcpu-1gb-sgp1-01 python[301306]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:55:39 ubuntu-s-1vcpu-1gb-sgp1-01 python[301308]: Traceback (most recent call last):
Aug 30 20:55:39 ubuntu-s-1vcpu-1gb-sgp1-01 python[301308]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:55:39 ubuntu-s-1vcpu-1gb-sgp1-01 python[301308]:     bot = Bot(token=TOKEN)
Aug 30 20:55:39 ubuntu-s-1vcpu-1gb-sgp1-01 python[301308]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:55:39 ubuntu-s-1vcpu-1gb-sgp1-01 python[301308]:     api.check_token(token)
Aug 30 20:55:39 ubuntu-s-1vcpu-1gb-sgp1-01 python[301308]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:55:39 ubuntu-s-1vcpu-1gb-sgp1-01 python[301308]:     raise exceptions.ValidationError(message)
Aug 30 20:55:39 ubuntu-s-1vcpu-1gb-sgp1-01 python[301308]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:55:41 ubuntu-s-1vcpu-1gb-sgp1-01 python[301311]: Traceback (most recent call last):
Aug 30 20:55:41 ubuntu-s-1vcpu-1gb-sgp1-01 python[301311]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:55:41 ubuntu-s-1vcpu-1gb-sgp1-01 python[301311]:     bot = Bot(token=TOKEN)
Aug 30 20:55:41 ubuntu-s-1vcpu-1gb-sgp1-01 python[301311]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:55:41 ubuntu-s-1vcpu-1gb-sgp1-01 python[301311]:     api.check_token(token)
Aug 30 20:55:41 ubuntu-s-1vcpu-1gb-sgp1-01 python[301311]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:55:41 ubuntu-s-1vcpu-1gb-sgp1-01 python[301311]:     raise exceptions.ValidationError(message)
Aug 30 20:55:41 ubuntu-s-1vcpu-1gb-sgp1-01 python[301311]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:55:44 ubuntu-s-1vcpu-1gb-sgp1-01 python[301315]: Traceback (most recent call last):
Aug 30 20:55:44 ubuntu-s-1vcpu-1gb-sgp1-01 python[301315]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:55:44 ubuntu-s-1vcpu-1gb-sgp1-01 python[301315]:     bot = Bot(token=TOKEN)
Aug 30 20:55:44 ubuntu-s-1vcpu-1gb-sgp1-01 python[301315]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:55:44 ubuntu-s-1vcpu-1gb-sgp1-01 python[301315]:     api.check_token(token)
Aug 30 20:55:44 ubuntu-s-1vcpu-1gb-sgp1-01 python[301315]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:55:44 ubuntu-s-1vcpu-1gb-sgp1-01 python[301315]:     raise exceptions.ValidationError(message)
Aug 30 20:55:44 ubuntu-s-1vcpu-1gb-sgp1-01 python[301315]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:55:46 ubuntu-s-1vcpu-1gb-sgp1-01 python[301317]: Traceback (most recent call last):
Aug 30 20:55:46 ubuntu-s-1vcpu-1gb-sgp1-01 python[301317]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:55:46 ubuntu-s-1vcpu-1gb-sgp1-01 python[301317]:     bot = Bot(token=TOKEN)
Aug 30 20:55:46 ubuntu-s-1vcpu-1gb-sgp1-01 python[301317]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:55:46 ubuntu-s-1vcpu-1gb-sgp1-01 python[301317]:     api.check_token(token)
Aug 30 20:55:46 ubuntu-s-1vcpu-1gb-sgp1-01 python[301317]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:55:46 ubuntu-s-1vcpu-1gb-sgp1-01 python[301317]:     raise exceptions.ValidationError(message)
Aug 30 20:55:46 ubuntu-s-1vcpu-1gb-sgp1-01 python[301317]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:55:49 ubuntu-s-1vcpu-1gb-sgp1-01 python[301318]: Traceback (most recent call last):
Aug 30 20:55:49 ubuntu-s-1vcpu-1gb-sgp1-01 python[301318]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:55:49 ubuntu-s-1vcpu-1gb-sgp1-01 python[301318]:     bot = Bot(token=TOKEN)
Aug 30 20:55:49 ubuntu-s-1vcpu-1gb-sgp1-01 python[301318]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:55:49 ubuntu-s-1vcpu-1gb-sgp1-01 python[301318]:     api.check_token(token)
Aug 30 20:55:49 ubuntu-s-1vcpu-1gb-sgp1-01 python[301318]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:55:49 ubuntu-s-1vcpu-1gb-sgp1-01 python[301318]:     raise exceptions.ValidationError(message)
Aug 30 20:55:49 ubuntu-s-1vcpu-1gb-sgp1-01 python[301318]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:55:51 ubuntu-s-1vcpu-1gb-sgp1-01 python[301324]: Traceback (most recent call last):
Aug 30 20:55:51 ubuntu-s-1vcpu-1gb-sgp1-01 python[301324]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:55:51 ubuntu-s-1vcpu-1gb-sgp1-01 python[301324]:     bot = Bot(token=TOKEN)
Aug 30 20:55:51 ubuntu-s-1vcpu-1gb-sgp1-01 python[301324]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:55:51 ubuntu-s-1vcpu-1gb-sgp1-01 python[301324]:     api.check_token(token)
Aug 30 20:55:51 ubuntu-s-1vcpu-1gb-sgp1-01 python[301324]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:55:51 ubuntu-s-1vcpu-1gb-sgp1-01 python[301324]:     raise exceptions.ValidationError(message)
Aug 30 20:55:51 ubuntu-s-1vcpu-1gb-sgp1-01 python[301324]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:55:54 ubuntu-s-1vcpu-1gb-sgp1-01 python[301327]: Traceback (most recent call last):
Aug 30 20:55:54 ubuntu-s-1vcpu-1gb-sgp1-01 python[301327]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:55:54 ubuntu-s-1vcpu-1gb-sgp1-01 python[301327]:     bot = Bot(token=TOKEN)
Aug 30 20:55:54 ubuntu-s-1vcpu-1gb-sgp1-01 python[301327]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:55:54 ubuntu-s-1vcpu-1gb-sgp1-01 python[301327]:     api.check_token(token)
Aug 30 20:55:54 ubuntu-s-1vcpu-1gb-sgp1-01 python[301327]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:55:54 ubuntu-s-1vcpu-1gb-sgp1-01 python[301327]:     raise exceptions.ValidationError(message)
Aug 30 20:55:54 ubuntu-s-1vcpu-1gb-sgp1-01 python[301327]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:55:57 ubuntu-s-1vcpu-1gb-sgp1-01 python[301331]: Traceback (most recent call last):
Aug 30 20:55:57 ubuntu-s-1vcpu-1gb-sgp1-01 python[301331]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:55:57 ubuntu-s-1vcpu-1gb-sgp1-01 python[301331]:     bot = Bot(token=TOKEN)
Aug 30 20:55:57 ubuntu-s-1vcpu-1gb-sgp1-01 python[301331]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:55:57 ubuntu-s-1vcpu-1gb-sgp1-01 python[301331]:     api.check_token(token)
Aug 30 20:55:57 ubuntu-s-1vcpu-1gb-sgp1-01 python[301331]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:55:57 ubuntu-s-1vcpu-1gb-sgp1-01 python[301331]:     raise exceptions.ValidationError(message)
Aug 30 20:55:57 ubuntu-s-1vcpu-1gb-sgp1-01 python[301331]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:55:59 ubuntu-s-1vcpu-1gb-sgp1-01 python[301337]: Traceback (most recent call last):
Aug 30 20:55:59 ubuntu-s-1vcpu-1gb-sgp1-01 python[301337]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:55:59 ubuntu-s-1vcpu-1gb-sgp1-01 python[301337]:     bot = Bot(token=TOKEN)
Aug 30 20:55:59 ubuntu-s-1vcpu-1gb-sgp1-01 python[301337]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:55:59 ubuntu-s-1vcpu-1gb-sgp1-01 python[301337]:     api.check_token(token)
Aug 30 20:55:59 ubuntu-s-1vcpu-1gb-sgp1-01 python[301337]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:55:59 ubuntu-s-1vcpu-1gb-sgp1-01 python[301337]:     raise exceptions.ValidationError(message)
Aug 30 20:55:59 ubuntu-s-1vcpu-1gb-sgp1-01 python[301337]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:56:02 ubuntu-s-1vcpu-1gb-sgp1-01 python[301340]: Traceback (most recent call last):
Aug 30 20:56:02 ubuntu-s-1vcpu-1gb-sgp1-01 python[301340]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:56:02 ubuntu-s-1vcpu-1gb-sgp1-01 python[301340]:     bot = Bot(token=TOKEN)
Aug 30 20:56:02 ubuntu-s-1vcpu-1gb-sgp1-01 python[301340]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:56:02 ubuntu-s-1vcpu-1gb-sgp1-01 python[301340]:     api.check_token(token)
Aug 30 20:56:02 ubuntu-s-1vcpu-1gb-sgp1-01 python[301340]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:56:02 ubuntu-s-1vcpu-1gb-sgp1-01 python[301340]:     raise exceptions.ValidationError(message)
Aug 30 20:56:02 ubuntu-s-1vcpu-1gb-sgp1-01 python[301340]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:56:05 ubuntu-s-1vcpu-1gb-sgp1-01 python[301341]: Traceback (most recent call last):
Aug 30 20:56:05 ubuntu-s-1vcpu-1gb-sgp1-01 python[301341]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:56:05 ubuntu-s-1vcpu-1gb-sgp1-01 python[301341]:     bot = Bot(token=TOKEN)
Aug 30 20:56:05 ubuntu-s-1vcpu-1gb-sgp1-01 python[301341]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:56:05 ubuntu-s-1vcpu-1gb-sgp1-01 python[301341]:     api.check_token(token)
Aug 30 20:56:05 ubuntu-s-1vcpu-1gb-sgp1-01 python[301341]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:56:05 ubuntu-s-1vcpu-1gb-sgp1-01 python[301341]:     raise exceptions.ValidationError(message)
Aug 30 20:56:05 ubuntu-s-1vcpu-1gb-sgp1-01 python[301341]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:56:07 ubuntu-s-1vcpu-1gb-sgp1-01 python[301343]: Traceback (most recent call last):
Aug 30 20:56:07 ubuntu-s-1vcpu-1gb-sgp1-01 python[301343]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:56:07 ubuntu-s-1vcpu-1gb-sgp1-01 python[301343]:     bot = Bot(token=TOKEN)
Aug 30 20:56:07 ubuntu-s-1vcpu-1gb-sgp1-01 python[301343]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:56:07 ubuntu-s-1vcpu-1gb-sgp1-01 python[301343]:     api.check_token(token)
Aug 30 20:56:07 ubuntu-s-1vcpu-1gb-sgp1-01 python[301343]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:56:07 ubuntu-s-1vcpu-1gb-sgp1-01 python[301343]:     raise exceptions.ValidationError(message)
Aug 30 20:56:07 ubuntu-s-1vcpu-1gb-sgp1-01 python[301343]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:56:10 ubuntu-s-1vcpu-1gb-sgp1-01 python[301347]: Traceback (most recent call last):
Aug 30 20:56:10 ubuntu-s-1vcpu-1gb-sgp1-01 python[301347]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:56:10 ubuntu-s-1vcpu-1gb-sgp1-01 python[301347]:     bot = Bot(token=TOKEN)
Aug 30 20:56:10 ubuntu-s-1vcpu-1gb-sgp1-01 python[301347]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:56:10 ubuntu-s-1vcpu-1gb-sgp1-01 python[301347]:     api.check_token(token)
Aug 30 20:56:10 ubuntu-s-1vcpu-1gb-sgp1-01 python[301347]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:56:10 ubuntu-s-1vcpu-1gb-sgp1-01 python[301347]:     raise exceptions.ValidationError(message)
Aug 30 20:56:10 ubuntu-s-1vcpu-1gb-sgp1-01 python[301347]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:56:13 ubuntu-s-1vcpu-1gb-sgp1-01 python[301351]: Traceback (most recent call last):
Aug 30 20:56:13 ubuntu-s-1vcpu-1gb-sgp1-01 python[301351]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:56:13 ubuntu-s-1vcpu-1gb-sgp1-01 python[301351]:     bot = Bot(token=TOKEN)
Aug 30 20:56:13 ubuntu-s-1vcpu-1gb-sgp1-01 python[301351]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:56:13 ubuntu-s-1vcpu-1gb-sgp1-01 python[301351]:     api.check_token(token)
Aug 30 20:56:13 ubuntu-s-1vcpu-1gb-sgp1-01 python[301351]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:56:13 ubuntu-s-1vcpu-1gb-sgp1-01 python[301351]:     raise exceptions.ValidationError(message)
Aug 30 20:56:13 ubuntu-s-1vcpu-1gb-sgp1-01 python[301351]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:56:15 ubuntu-s-1vcpu-1gb-sgp1-01 python[301353]: Traceback (most recent call last):
Aug 30 20:56:15 ubuntu-s-1vcpu-1gb-sgp1-01 python[301353]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:56:15 ubuntu-s-1vcpu-1gb-sgp1-01 python[301353]:     bot = Bot(token=TOKEN)
Aug 30 20:56:15 ubuntu-s-1vcpu-1gb-sgp1-01 python[301353]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:56:15 ubuntu-s-1vcpu-1gb-sgp1-01 python[301353]:     api.check_token(token)
Aug 30 20:56:15 ubuntu-s-1vcpu-1gb-sgp1-01 python[301353]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:56:15 ubuntu-s-1vcpu-1gb-sgp1-01 python[301353]:     raise exceptions.ValidationError(message)
Aug 30 20:56:15 ubuntu-s-1vcpu-1gb-sgp1-01 python[301353]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:56:18 ubuntu-s-1vcpu-1gb-sgp1-01 python[301358]: Traceback (most recent call last):
Aug 30 20:56:18 ubuntu-s-1vcpu-1gb-sgp1-01 python[301358]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:56:18 ubuntu-s-1vcpu-1gb-sgp1-01 python[301358]:     bot = Bot(token=TOKEN)
Aug 30 20:56:18 ubuntu-s-1vcpu-1gb-sgp1-01 python[301358]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:56:18 ubuntu-s-1vcpu-1gb-sgp1-01 python[301358]:     api.check_token(token)
Aug 30 20:56:18 ubuntu-s-1vcpu-1gb-sgp1-01 python[301358]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:56:18 ubuntu-s-1vcpu-1gb-sgp1-01 python[301358]:     raise exceptions.ValidationError(message)
Aug 30 20:56:18 ubuntu-s-1vcpu-1gb-sgp1-01 python[301358]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:56:21 ubuntu-s-1vcpu-1gb-sgp1-01 python[301360]: Traceback (most recent call last):
Aug 30 20:56:21 ubuntu-s-1vcpu-1gb-sgp1-01 python[301360]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:56:21 ubuntu-s-1vcpu-1gb-sgp1-01 python[301360]:     bot = Bot(token=TOKEN)
Aug 30 20:56:21 ubuntu-s-1vcpu-1gb-sgp1-01 python[301360]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:56:21 ubuntu-s-1vcpu-1gb-sgp1-01 python[301360]:     api.check_token(token)
Aug 30 20:56:21 ubuntu-s-1vcpu-1gb-sgp1-01 python[301360]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:56:21 ubuntu-s-1vcpu-1gb-sgp1-01 python[301360]:     raise exceptions.ValidationError(message)
Aug 30 20:56:21 ubuntu-s-1vcpu-1gb-sgp1-01 python[301360]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:56:23 ubuntu-s-1vcpu-1gb-sgp1-01 python[301361]: Traceback (most recent call last):
Aug 30 20:56:23 ubuntu-s-1vcpu-1gb-sgp1-01 python[301361]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:56:23 ubuntu-s-1vcpu-1gb-sgp1-01 python[301361]:     bot = Bot(token=TOKEN)
Aug 30 20:56:23 ubuntu-s-1vcpu-1gb-sgp1-01 python[301361]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:56:23 ubuntu-s-1vcpu-1gb-sgp1-01 python[301361]:     api.check_token(token)
Aug 30 20:56:23 ubuntu-s-1vcpu-1gb-sgp1-01 python[301361]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:56:23 ubuntu-s-1vcpu-1gb-sgp1-01 python[301361]:     raise exceptions.ValidationError(message)
Aug 30 20:56:23 ubuntu-s-1vcpu-1gb-sgp1-01 python[301361]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:56:26 ubuntu-s-1vcpu-1gb-sgp1-01 python[301365]: Traceback (most recent call last):
Aug 30 20:56:26 ubuntu-s-1vcpu-1gb-sgp1-01 python[301365]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:56:26 ubuntu-s-1vcpu-1gb-sgp1-01 python[301365]:     bot = Bot(token=TOKEN)
Aug 30 20:56:26 ubuntu-s-1vcpu-1gb-sgp1-01 python[301365]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:56:26 ubuntu-s-1vcpu-1gb-sgp1-01 python[301365]:     api.check_token(token)
Aug 30 20:56:26 ubuntu-s-1vcpu-1gb-sgp1-01 python[301365]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:56:26 ubuntu-s-1vcpu-1gb-sgp1-01 python[301365]:     raise exceptions.ValidationError(message)
Aug 30 20:56:26 ubuntu-s-1vcpu-1gb-sgp1-01 python[301365]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:56:29 ubuntu-s-1vcpu-1gb-sgp1-01 python[301369]: Traceback (most recent call last):
Aug 30 20:56:29 ubuntu-s-1vcpu-1gb-sgp1-01 python[301369]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:56:29 ubuntu-s-1vcpu-1gb-sgp1-01 python[301369]:     bot = Bot(token=TOKEN)
Aug 30 20:56:29 ubuntu-s-1vcpu-1gb-sgp1-01 python[301369]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:56:29 ubuntu-s-1vcpu-1gb-sgp1-01 python[301369]:     api.check_token(token)
Aug 30 20:56:29 ubuntu-s-1vcpu-1gb-sgp1-01 python[301369]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:56:29 ubuntu-s-1vcpu-1gb-sgp1-01 python[301369]:     raise exceptions.ValidationError(message)
Aug 30 20:56:29 ubuntu-s-1vcpu-1gb-sgp1-01 python[301369]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:56:31 ubuntu-s-1vcpu-1gb-sgp1-01 python[301370]: Traceback (most recent call last):
Aug 30 20:56:31 ubuntu-s-1vcpu-1gb-sgp1-01 python[301370]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:56:31 ubuntu-s-1vcpu-1gb-sgp1-01 python[301370]:     bot = Bot(token=TOKEN)
Aug 30 20:56:31 ubuntu-s-1vcpu-1gb-sgp1-01 python[301370]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:56:31 ubuntu-s-1vcpu-1gb-sgp1-01 python[301370]:     api.check_token(token)
Aug 30 20:56:31 ubuntu-s-1vcpu-1gb-sgp1-01 python[301370]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:56:31 ubuntu-s-1vcpu-1gb-sgp1-01 python[301370]:     raise exceptions.ValidationError(message)
Aug 30 20:56:31 ubuntu-s-1vcpu-1gb-sgp1-01 python[301370]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:56:34 ubuntu-s-1vcpu-1gb-sgp1-01 python[301374]: Traceback (most recent call last):
Aug 30 20:56:34 ubuntu-s-1vcpu-1gb-sgp1-01 python[301374]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:56:34 ubuntu-s-1vcpu-1gb-sgp1-01 python[301374]:     bot = Bot(token=TOKEN)
Aug 30 20:56:34 ubuntu-s-1vcpu-1gb-sgp1-01 python[301374]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:56:34 ubuntu-s-1vcpu-1gb-sgp1-01 python[301374]:     api.check_token(token)
Aug 30 20:56:34 ubuntu-s-1vcpu-1gb-sgp1-01 python[301374]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:56:34 ubuntu-s-1vcpu-1gb-sgp1-01 python[301374]:     raise exceptions.ValidationError(message)
Aug 30 20:56:34 ubuntu-s-1vcpu-1gb-sgp1-01 python[301374]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:56:36 ubuntu-s-1vcpu-1gb-sgp1-01 python[301376]: Traceback (most recent call last):
Aug 30 20:56:36 ubuntu-s-1vcpu-1gb-sgp1-01 python[301376]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:56:36 ubuntu-s-1vcpu-1gb-sgp1-01 python[301376]:     bot = Bot(token=TOKEN)
Aug 30 20:56:36 ubuntu-s-1vcpu-1gb-sgp1-01 python[301376]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:56:36 ubuntu-s-1vcpu-1gb-sgp1-01 python[301376]:     api.check_token(token)
Aug 30 20:56:36 ubuntu-s-1vcpu-1gb-sgp1-01 python[301376]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:56:36 ubuntu-s-1vcpu-1gb-sgp1-01 python[301376]:     raise exceptions.ValidationError(message)
Aug 30 20:56:36 ubuntu-s-1vcpu-1gb-sgp1-01 python[301376]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:56:39 ubuntu-s-1vcpu-1gb-sgp1-01 python[301378]: Traceback (most recent call last):
Aug 30 20:56:39 ubuntu-s-1vcpu-1gb-sgp1-01 python[301378]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:56:39 ubuntu-s-1vcpu-1gb-sgp1-01 python[301378]:     bot = Bot(token=TOKEN)
Aug 30 20:56:39 ubuntu-s-1vcpu-1gb-sgp1-01 python[301378]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:56:39 ubuntu-s-1vcpu-1gb-sgp1-01 python[301378]:     api.check_token(token)
Aug 30 20:56:39 ubuntu-s-1vcpu-1gb-sgp1-01 python[301378]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:56:39 ubuntu-s-1vcpu-1gb-sgp1-01 python[301378]:     raise exceptions.ValidationError(message)
Aug 30 20:56:39 ubuntu-s-1vcpu-1gb-sgp1-01 python[301378]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:56:41 ubuntu-s-1vcpu-1gb-sgp1-01 python[301383]: Traceback (most recent call last):
Aug 30 20:56:41 ubuntu-s-1vcpu-1gb-sgp1-01 python[301383]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:56:41 ubuntu-s-1vcpu-1gb-sgp1-01 python[301383]:     bot = Bot(token=TOKEN)
Aug 30 20:56:41 ubuntu-s-1vcpu-1gb-sgp1-01 python[301383]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:56:41 ubuntu-s-1vcpu-1gb-sgp1-01 python[301383]:     api.check_token(token)
Aug 30 20:56:41 ubuntu-s-1vcpu-1gb-sgp1-01 python[301383]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:56:41 ubuntu-s-1vcpu-1gb-sgp1-01 python[301383]:     raise exceptions.ValidationError(message)
Aug 30 20:56:41 ubuntu-s-1vcpu-1gb-sgp1-01 python[301383]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:56:44 ubuntu-s-1vcpu-1gb-sgp1-01 python[301387]: Traceback (most recent call last):
Aug 30 20:56:44 ubuntu-s-1vcpu-1gb-sgp1-01 python[301387]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:56:44 ubuntu-s-1vcpu-1gb-sgp1-01 python[301387]:     bot = Bot(token=TOKEN)
Aug 30 20:56:44 ubuntu-s-1vcpu-1gb-sgp1-01 python[301387]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:56:44 ubuntu-s-1vcpu-1gb-sgp1-01 python[301387]:     api.check_token(token)
Aug 30 20:56:44 ubuntu-s-1vcpu-1gb-sgp1-01 python[301387]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:56:44 ubuntu-s-1vcpu-1gb-sgp1-01 python[301387]:     raise exceptions.ValidationError(message)
Aug 30 20:56:44 ubuntu-s-1vcpu-1gb-sgp1-01 python[301387]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:56:46 ubuntu-s-1vcpu-1gb-sgp1-01 python[301388]: Traceback (most recent call last):
Aug 30 20:56:46 ubuntu-s-1vcpu-1gb-sgp1-01 python[301388]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:56:46 ubuntu-s-1vcpu-1gb-sgp1-01 python[301388]:     bot = Bot(token=TOKEN)
Aug 30 20:56:46 ubuntu-s-1vcpu-1gb-sgp1-01 python[301388]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:56:46 ubuntu-s-1vcpu-1gb-sgp1-01 python[301388]:     api.check_token(token)
Aug 30 20:56:46 ubuntu-s-1vcpu-1gb-sgp1-01 python[301388]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:56:46 ubuntu-s-1vcpu-1gb-sgp1-01 python[301388]:     raise exceptions.ValidationError(message)
Aug 30 20:56:46 ubuntu-s-1vcpu-1gb-sgp1-01 python[301388]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:56:49 ubuntu-s-1vcpu-1gb-sgp1-01 python[301393]: Traceback (most recent call last):
Aug 30 20:56:49 ubuntu-s-1vcpu-1gb-sgp1-01 python[301393]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:56:49 ubuntu-s-1vcpu-1gb-sgp1-01 python[301393]:     bot = Bot(token=TOKEN)
Aug 30 20:56:49 ubuntu-s-1vcpu-1gb-sgp1-01 python[301393]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:56:49 ubuntu-s-1vcpu-1gb-sgp1-01 python[301393]:     api.check_token(token)
Aug 30 20:56:49 ubuntu-s-1vcpu-1gb-sgp1-01 python[301393]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:56:49 ubuntu-s-1vcpu-1gb-sgp1-01 python[301393]:     raise exceptions.ValidationError(message)
Aug 30 20:56:49 ubuntu-s-1vcpu-1gb-sgp1-01 python[301393]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:56:51 ubuntu-s-1vcpu-1gb-sgp1-01 python[301396]: Traceback (most recent call last):
Aug 30 20:56:51 ubuntu-s-1vcpu-1gb-sgp1-01 python[301396]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:56:51 ubuntu-s-1vcpu-1gb-sgp1-01 python[301396]:     bot = Bot(token=TOKEN)
Aug 30 20:56:51 ubuntu-s-1vcpu-1gb-sgp1-01 python[301396]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:56:51 ubuntu-s-1vcpu-1gb-sgp1-01 python[301396]:     api.check_token(token)
Aug 30 20:56:51 ubuntu-s-1vcpu-1gb-sgp1-01 python[301396]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:56:51 ubuntu-s-1vcpu-1gb-sgp1-01 python[301396]:     raise exceptions.ValidationError(message)
Aug 30 20:56:51 ubuntu-s-1vcpu-1gb-sgp1-01 python[301396]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:56:54 ubuntu-s-1vcpu-1gb-sgp1-01 python[301397]: Traceback (most recent call last):
Aug 30 20:56:54 ubuntu-s-1vcpu-1gb-sgp1-01 python[301397]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:56:54 ubuntu-s-1vcpu-1gb-sgp1-01 python[301397]:     bot = Bot(token=TOKEN)
Aug 30 20:56:54 ubuntu-s-1vcpu-1gb-sgp1-01 python[301397]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:56:54 ubuntu-s-1vcpu-1gb-sgp1-01 python[301397]:     api.check_token(token)
Aug 30 20:56:54 ubuntu-s-1vcpu-1gb-sgp1-01 python[301397]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:56:54 ubuntu-s-1vcpu-1gb-sgp1-01 python[301397]:     raise exceptions.ValidationError(message)
Aug 30 20:56:54 ubuntu-s-1vcpu-1gb-sgp1-01 python[301397]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:56:56 ubuntu-s-1vcpu-1gb-sgp1-01 python[301401]: Traceback (most recent call last):
Aug 30 20:56:56 ubuntu-s-1vcpu-1gb-sgp1-01 python[301401]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:56:56 ubuntu-s-1vcpu-1gb-sgp1-01 python[301401]:     bot = Bot(token=TOKEN)
Aug 30 20:56:56 ubuntu-s-1vcpu-1gb-sgp1-01 python[301401]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:56:56 ubuntu-s-1vcpu-1gb-sgp1-01 python[301401]:     api.check_token(token)
Aug 30 20:56:56 ubuntu-s-1vcpu-1gb-sgp1-01 python[301401]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:56:56 ubuntu-s-1vcpu-1gb-sgp1-01 python[301401]:     raise exceptions.ValidationError(message)
Aug 30 20:56:56 ubuntu-s-1vcpu-1gb-sgp1-01 python[301401]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:56:59 ubuntu-s-1vcpu-1gb-sgp1-01 python[301407]: Traceback (most recent call last):
Aug 30 20:56:59 ubuntu-s-1vcpu-1gb-sgp1-01 python[301407]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:56:59 ubuntu-s-1vcpu-1gb-sgp1-01 python[301407]:     bot = Bot(token=TOKEN)
Aug 30 20:56:59 ubuntu-s-1vcpu-1gb-sgp1-01 python[301407]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:56:59 ubuntu-s-1vcpu-1gb-sgp1-01 python[301407]:     api.check_token(token)
Aug 30 20:56:59 ubuntu-s-1vcpu-1gb-sgp1-01 python[301407]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:56:59 ubuntu-s-1vcpu-1gb-sgp1-01 python[301407]:     raise exceptions.ValidationError(message)
Aug 30 20:56:59 ubuntu-s-1vcpu-1gb-sgp1-01 python[301407]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:57:01 ubuntu-s-1vcpu-1gb-sgp1-01 python[301409]: Traceback (most recent call last):
Aug 30 20:57:01 ubuntu-s-1vcpu-1gb-sgp1-01 python[301409]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:57:01 ubuntu-s-1vcpu-1gb-sgp1-01 python[301409]:     bot = Bot(token=TOKEN)
Aug 30 20:57:01 ubuntu-s-1vcpu-1gb-sgp1-01 python[301409]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:57:01 ubuntu-s-1vcpu-1gb-sgp1-01 python[301409]:     api.check_token(token)
Aug 30 20:57:01 ubuntu-s-1vcpu-1gb-sgp1-01 python[301409]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:57:01 ubuntu-s-1vcpu-1gb-sgp1-01 python[301409]:     raise exceptions.ValidationError(message)
Aug 30 20:57:01 ubuntu-s-1vcpu-1gb-sgp1-01 python[301409]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:57:04 ubuntu-s-1vcpu-1gb-sgp1-01 python[301412]: Traceback (most recent call last):
Aug 30 20:57:04 ubuntu-s-1vcpu-1gb-sgp1-01 python[301412]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:57:04 ubuntu-s-1vcpu-1gb-sgp1-01 python[301412]:     bot = Bot(token=TOKEN)
Aug 30 20:57:04 ubuntu-s-1vcpu-1gb-sgp1-01 python[301412]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:57:04 ubuntu-s-1vcpu-1gb-sgp1-01 python[301412]:     api.check_token(token)
Aug 30 20:57:04 ubuntu-s-1vcpu-1gb-sgp1-01 python[301412]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:57:04 ubuntu-s-1vcpu-1gb-sgp1-01 python[301412]:     raise exceptions.ValidationError(message)
Aug 30 20:57:04 ubuntu-s-1vcpu-1gb-sgp1-01 python[301412]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:57:06 ubuntu-s-1vcpu-1gb-sgp1-01 python[301414]: Traceback (most recent call last):
Aug 30 20:57:06 ubuntu-s-1vcpu-1gb-sgp1-01 python[301414]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:57:06 ubuntu-s-1vcpu-1gb-sgp1-01 python[301414]:     bot = Bot(token=TOKEN)
Aug 30 20:57:06 ubuntu-s-1vcpu-1gb-sgp1-01 python[301414]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:57:06 ubuntu-s-1vcpu-1gb-sgp1-01 python[301414]:     api.check_token(token)
Aug 30 20:57:06 ubuntu-s-1vcpu-1gb-sgp1-01 python[301414]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:57:06 ubuntu-s-1vcpu-1gb-sgp1-01 python[301414]:     raise exceptions.ValidationError(message)
Aug 30 20:57:06 ubuntu-s-1vcpu-1gb-sgp1-01 python[301414]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:57:09 ubuntu-s-1vcpu-1gb-sgp1-01 python[301417]: Traceback (most recent call last):
Aug 30 20:57:09 ubuntu-s-1vcpu-1gb-sgp1-01 python[301417]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:57:09 ubuntu-s-1vcpu-1gb-sgp1-01 python[301417]:     bot = Bot(token=TOKEN)
Aug 30 20:57:09 ubuntu-s-1vcpu-1gb-sgp1-01 python[301417]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:57:09 ubuntu-s-1vcpu-1gb-sgp1-01 python[301417]:     api.check_token(token)
Aug 30 20:57:09 ubuntu-s-1vcpu-1gb-sgp1-01 python[301417]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:57:09 ubuntu-s-1vcpu-1gb-sgp1-01 python[301417]:     raise exceptions.ValidationError(message)
Aug 30 20:57:09 ubuntu-s-1vcpu-1gb-sgp1-01 python[301417]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:57:11 ubuntu-s-1vcpu-1gb-sgp1-01 python[301419]: Traceback (most recent call last):
Aug 30 20:57:11 ubuntu-s-1vcpu-1gb-sgp1-01 python[301419]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:57:11 ubuntu-s-1vcpu-1gb-sgp1-01 python[301419]:     bot = Bot(token=TOKEN)
Aug 30 20:57:11 ubuntu-s-1vcpu-1gb-sgp1-01 python[301419]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:57:11 ubuntu-s-1vcpu-1gb-sgp1-01 python[301419]:     api.check_token(token)
Aug 30 20:57:11 ubuntu-s-1vcpu-1gb-sgp1-01 python[301419]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:57:11 ubuntu-s-1vcpu-1gb-sgp1-01 python[301419]:     raise exceptions.ValidationError(message)
Aug 30 20:57:11 ubuntu-s-1vcpu-1gb-sgp1-01 python[301419]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:57:14 ubuntu-s-1vcpu-1gb-sgp1-01 python[301423]: Traceback (most recent call last):
Aug 30 20:57:14 ubuntu-s-1vcpu-1gb-sgp1-01 python[301423]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:57:14 ubuntu-s-1vcpu-1gb-sgp1-01 python[301423]:     bot = Bot(token=TOKEN)
Aug 30 20:57:14 ubuntu-s-1vcpu-1gb-sgp1-01 python[301423]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:57:14 ubuntu-s-1vcpu-1gb-sgp1-01 python[301423]:     api.check_token(token)
Aug 30 20:57:14 ubuntu-s-1vcpu-1gb-sgp1-01 python[301423]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:57:14 ubuntu-s-1vcpu-1gb-sgp1-01 python[301423]:     raise exceptions.ValidationError(message)
Aug 30 20:57:14 ubuntu-s-1vcpu-1gb-sgp1-01 python[301423]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:57:16 ubuntu-s-1vcpu-1gb-sgp1-01 python[301426]: Traceback (most recent call last):
Aug 30 20:57:16 ubuntu-s-1vcpu-1gb-sgp1-01 python[301426]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:57:16 ubuntu-s-1vcpu-1gb-sgp1-01 python[301426]:     bot = Bot(token=TOKEN)
Aug 30 20:57:16 ubuntu-s-1vcpu-1gb-sgp1-01 python[301426]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:57:16 ubuntu-s-1vcpu-1gb-sgp1-01 python[301426]:     api.check_token(token)
Aug 30 20:57:16 ubuntu-s-1vcpu-1gb-sgp1-01 python[301426]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:57:16 ubuntu-s-1vcpu-1gb-sgp1-01 python[301426]:     raise exceptions.ValidationError(message)
Aug 30 20:57:16 ubuntu-s-1vcpu-1gb-sgp1-01 python[301426]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:57:19 ubuntu-s-1vcpu-1gb-sgp1-01 python[301428]: Traceback (most recent call last):
Aug 30 20:57:19 ubuntu-s-1vcpu-1gb-sgp1-01 python[301428]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:57:19 ubuntu-s-1vcpu-1gb-sgp1-01 python[301428]:     bot = Bot(token=TOKEN)
Aug 30 20:57:19 ubuntu-s-1vcpu-1gb-sgp1-01 python[301428]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:57:19 ubuntu-s-1vcpu-1gb-sgp1-01 python[301428]:     api.check_token(token)
Aug 30 20:57:19 ubuntu-s-1vcpu-1gb-sgp1-01 python[301428]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:57:19 ubuntu-s-1vcpu-1gb-sgp1-01 python[301428]:     raise exceptions.ValidationError(message)
Aug 30 20:57:19 ubuntu-s-1vcpu-1gb-sgp1-01 python[301428]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:57:22 ubuntu-s-1vcpu-1gb-sgp1-01 python[301432]: Traceback (most recent call last):
Aug 30 20:57:22 ubuntu-s-1vcpu-1gb-sgp1-01 python[301432]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:57:22 ubuntu-s-1vcpu-1gb-sgp1-01 python[301432]:     bot = Bot(token=TOKEN)
Aug 30 20:57:22 ubuntu-s-1vcpu-1gb-sgp1-01 python[301432]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:57:22 ubuntu-s-1vcpu-1gb-sgp1-01 python[301432]:     api.check_token(token)
Aug 30 20:57:22 ubuntu-s-1vcpu-1gb-sgp1-01 python[301432]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:57:22 ubuntu-s-1vcpu-1gb-sgp1-01 python[301432]:     raise exceptions.ValidationError(message)
Aug 30 20:57:22 ubuntu-s-1vcpu-1gb-sgp1-01 python[301432]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:57:24 ubuntu-s-1vcpu-1gb-sgp1-01 python[301435]: Traceback (most recent call last):
Aug 30 20:57:24 ubuntu-s-1vcpu-1gb-sgp1-01 python[301435]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:57:24 ubuntu-s-1vcpu-1gb-sgp1-01 python[301435]:     bot = Bot(token=TOKEN)
Aug 30 20:57:24 ubuntu-s-1vcpu-1gb-sgp1-01 python[301435]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:57:24 ubuntu-s-1vcpu-1gb-sgp1-01 python[301435]:     api.check_token(token)
Aug 30 20:57:24 ubuntu-s-1vcpu-1gb-sgp1-01 python[301435]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:57:24 ubuntu-s-1vcpu-1gb-sgp1-01 python[301435]:     raise exceptions.ValidationError(message)
Aug 30 20:57:24 ubuntu-s-1vcpu-1gb-sgp1-01 python[301435]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:57:27 ubuntu-s-1vcpu-1gb-sgp1-01 python[301438]: Traceback (most recent call last):
Aug 30 20:57:27 ubuntu-s-1vcpu-1gb-sgp1-01 python[301438]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:57:27 ubuntu-s-1vcpu-1gb-sgp1-01 python[301438]:     bot = Bot(token=TOKEN)
Aug 30 20:57:27 ubuntu-s-1vcpu-1gb-sgp1-01 python[301438]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:57:27 ubuntu-s-1vcpu-1gb-sgp1-01 python[301438]:     api.check_token(token)
Aug 30 20:57:27 ubuntu-s-1vcpu-1gb-sgp1-01 python[301438]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:57:27 ubuntu-s-1vcpu-1gb-sgp1-01 python[301438]:     raise exceptions.ValidationError(message)
Aug 30 20:57:27 ubuntu-s-1vcpu-1gb-sgp1-01 python[301438]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:57:29 ubuntu-s-1vcpu-1gb-sgp1-01 python[301441]: Traceback (most recent call last):
Aug 30 20:57:29 ubuntu-s-1vcpu-1gb-sgp1-01 python[301441]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:57:29 ubuntu-s-1vcpu-1gb-sgp1-01 python[301441]:     bot = Bot(token=TOKEN)
Aug 30 20:57:29 ubuntu-s-1vcpu-1gb-sgp1-01 python[301441]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:57:29 ubuntu-s-1vcpu-1gb-sgp1-01 python[301441]:     api.check_token(token)
Aug 30 20:57:29 ubuntu-s-1vcpu-1gb-sgp1-01 python[301441]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:57:29 ubuntu-s-1vcpu-1gb-sgp1-01 python[301441]:     raise exceptions.ValidationError(message)
Aug 30 20:57:29 ubuntu-s-1vcpu-1gb-sgp1-01 python[301441]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:57:32 ubuntu-s-1vcpu-1gb-sgp1-01 python[301446]: Traceback (most recent call last):
Aug 30 20:57:32 ubuntu-s-1vcpu-1gb-sgp1-01 python[301446]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:57:32 ubuntu-s-1vcpu-1gb-sgp1-01 python[301446]:     bot = Bot(token=TOKEN)
Aug 30 20:57:32 ubuntu-s-1vcpu-1gb-sgp1-01 python[301446]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:57:32 ubuntu-s-1vcpu-1gb-sgp1-01 python[301446]:     api.check_token(token)
Aug 30 20:57:32 ubuntu-s-1vcpu-1gb-sgp1-01 python[301446]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:57:32 ubuntu-s-1vcpu-1gb-sgp1-01 python[301446]:     raise exceptions.ValidationError(message)
Aug 30 20:57:32 ubuntu-s-1vcpu-1gb-sgp1-01 python[301446]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:57:35 ubuntu-s-1vcpu-1gb-sgp1-01 python[301448]: Traceback (most recent call last):
Aug 30 20:57:35 ubuntu-s-1vcpu-1gb-sgp1-01 python[301448]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:57:35 ubuntu-s-1vcpu-1gb-sgp1-01 python[301448]:     bot = Bot(token=TOKEN)
Aug 30 20:57:35 ubuntu-s-1vcpu-1gb-sgp1-01 python[301448]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:57:35 ubuntu-s-1vcpu-1gb-sgp1-01 python[301448]:     api.check_token(token)
Aug 30 20:57:35 ubuntu-s-1vcpu-1gb-sgp1-01 python[301448]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:57:35 ubuntu-s-1vcpu-1gb-sgp1-01 python[301448]:     raise exceptions.ValidationError(message)
Aug 30 20:57:35 ubuntu-s-1vcpu-1gb-sgp1-01 python[301448]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:57:37 ubuntu-s-1vcpu-1gb-sgp1-01 python[301450]: Traceback (most recent call last):
Aug 30 20:57:37 ubuntu-s-1vcpu-1gb-sgp1-01 python[301450]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:57:37 ubuntu-s-1vcpu-1gb-sgp1-01 python[301450]:     bot = Bot(token=TOKEN)
Aug 30 20:57:37 ubuntu-s-1vcpu-1gb-sgp1-01 python[301450]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:57:37 ubuntu-s-1vcpu-1gb-sgp1-01 python[301450]:     api.check_token(token)
Aug 30 20:57:37 ubuntu-s-1vcpu-1gb-sgp1-01 python[301450]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:57:37 ubuntu-s-1vcpu-1gb-sgp1-01 python[301450]:     raise exceptions.ValidationError(message)
Aug 30 20:57:37 ubuntu-s-1vcpu-1gb-sgp1-01 python[301450]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:57:40 ubuntu-s-1vcpu-1gb-sgp1-01 python[301453]: Traceback (most recent call last):
Aug 30 20:57:40 ubuntu-s-1vcpu-1gb-sgp1-01 python[301453]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:57:40 ubuntu-s-1vcpu-1gb-sgp1-01 python[301453]:     bot = Bot(token=TOKEN)
Aug 30 20:57:40 ubuntu-s-1vcpu-1gb-sgp1-01 python[301453]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:57:40 ubuntu-s-1vcpu-1gb-sgp1-01 python[301453]:     api.check_token(token)
Aug 30 20:57:40 ubuntu-s-1vcpu-1gb-sgp1-01 python[301453]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:57:40 ubuntu-s-1vcpu-1gb-sgp1-01 python[301453]:     raise exceptions.ValidationError(message)
Aug 30 20:57:40 ubuntu-s-1vcpu-1gb-sgp1-01 python[301453]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:57:43 ubuntu-s-1vcpu-1gb-sgp1-01 python[301455]: Traceback (most recent call last):
Aug 30 20:57:43 ubuntu-s-1vcpu-1gb-sgp1-01 python[301455]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:57:43 ubuntu-s-1vcpu-1gb-sgp1-01 python[301455]:     bot = Bot(token=TOKEN)
Aug 30 20:57:43 ubuntu-s-1vcpu-1gb-sgp1-01 python[301455]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:57:43 ubuntu-s-1vcpu-1gb-sgp1-01 python[301455]:     api.check_token(token)
Aug 30 20:57:43 ubuntu-s-1vcpu-1gb-sgp1-01 python[301455]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:57:43 ubuntu-s-1vcpu-1gb-sgp1-01 python[301455]:     raise exceptions.ValidationError(message)
Aug 30 20:57:43 ubuntu-s-1vcpu-1gb-sgp1-01 python[301455]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:57:45 ubuntu-s-1vcpu-1gb-sgp1-01 python[301460]: Traceback (most recent call last):
Aug 30 20:57:45 ubuntu-s-1vcpu-1gb-sgp1-01 python[301460]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:57:45 ubuntu-s-1vcpu-1gb-sgp1-01 python[301460]:     bot = Bot(token=TOKEN)
Aug 30 20:57:45 ubuntu-s-1vcpu-1gb-sgp1-01 python[301460]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:57:45 ubuntu-s-1vcpu-1gb-sgp1-01 python[301460]:     api.check_token(token)
Aug 30 20:57:45 ubuntu-s-1vcpu-1gb-sgp1-01 python[301460]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:57:45 ubuntu-s-1vcpu-1gb-sgp1-01 python[301460]:     raise exceptions.ValidationError(message)
Aug 30 20:57:45 ubuntu-s-1vcpu-1gb-sgp1-01 python[301460]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:57:48 ubuntu-s-1vcpu-1gb-sgp1-01 python[301465]: Traceback (most recent call last):
Aug 30 20:57:48 ubuntu-s-1vcpu-1gb-sgp1-01 python[301465]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:57:48 ubuntu-s-1vcpu-1gb-sgp1-01 python[301465]:     bot = Bot(token=TOKEN)
Aug 30 20:57:48 ubuntu-s-1vcpu-1gb-sgp1-01 python[301465]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:57:48 ubuntu-s-1vcpu-1gb-sgp1-01 python[301465]:     api.check_token(token)
Aug 30 20:57:48 ubuntu-s-1vcpu-1gb-sgp1-01 python[301465]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:57:48 ubuntu-s-1vcpu-1gb-sgp1-01 python[301465]:     raise exceptions.ValidationError(message)
Aug 30 20:57:48 ubuntu-s-1vcpu-1gb-sgp1-01 python[301465]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:57:51 ubuntu-s-1vcpu-1gb-sgp1-01 python[301468]: Traceback (most recent call last):
Aug 30 20:57:51 ubuntu-s-1vcpu-1gb-sgp1-01 python[301468]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:57:51 ubuntu-s-1vcpu-1gb-sgp1-01 python[301468]:     bot = Bot(token=TOKEN)
Aug 30 20:57:51 ubuntu-s-1vcpu-1gb-sgp1-01 python[301468]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:57:51 ubuntu-s-1vcpu-1gb-sgp1-01 python[301468]:     api.check_token(token)
Aug 30 20:57:51 ubuntu-s-1vcpu-1gb-sgp1-01 python[301468]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:57:51 ubuntu-s-1vcpu-1gb-sgp1-01 python[301468]:     raise exceptions.ValidationError(message)
Aug 30 20:57:51 ubuntu-s-1vcpu-1gb-sgp1-01 python[301468]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:57:53 ubuntu-s-1vcpu-1gb-sgp1-01 python[301473]: Traceback (most recent call last):
Aug 30 20:57:53 ubuntu-s-1vcpu-1gb-sgp1-01 python[301473]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:57:53 ubuntu-s-1vcpu-1gb-sgp1-01 python[301473]:     bot = Bot(token=TOKEN)
Aug 30 20:57:53 ubuntu-s-1vcpu-1gb-sgp1-01 python[301473]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:57:53 ubuntu-s-1vcpu-1gb-sgp1-01 python[301473]:     api.check_token(token)
Aug 30 20:57:53 ubuntu-s-1vcpu-1gb-sgp1-01 python[301473]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:57:53 ubuntu-s-1vcpu-1gb-sgp1-01 python[301473]:     raise exceptions.ValidationError(message)
Aug 30 20:57:53 ubuntu-s-1vcpu-1gb-sgp1-01 python[301473]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:57:56 ubuntu-s-1vcpu-1gb-sgp1-01 python[301475]: Traceback (most recent call last):
Aug 30 20:57:56 ubuntu-s-1vcpu-1gb-sgp1-01 python[301475]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:57:56 ubuntu-s-1vcpu-1gb-sgp1-01 python[301475]:     bot = Bot(token=TOKEN)
Aug 30 20:57:56 ubuntu-s-1vcpu-1gb-sgp1-01 python[301475]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:57:56 ubuntu-s-1vcpu-1gb-sgp1-01 python[301475]:     api.check_token(token)
Aug 30 20:57:56 ubuntu-s-1vcpu-1gb-sgp1-01 python[301475]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:57:56 ubuntu-s-1vcpu-1gb-sgp1-01 python[301475]:     raise exceptions.ValidationError(message)
Aug 30 20:57:56 ubuntu-s-1vcpu-1gb-sgp1-01 python[301475]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:57:58 ubuntu-s-1vcpu-1gb-sgp1-01 python[301478]: Traceback (most recent call last):
Aug 30 20:57:58 ubuntu-s-1vcpu-1gb-sgp1-01 python[301478]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:57:58 ubuntu-s-1vcpu-1gb-sgp1-01 python[301478]:     bot = Bot(token=TOKEN)
Aug 30 20:57:58 ubuntu-s-1vcpu-1gb-sgp1-01 python[301478]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:57:58 ubuntu-s-1vcpu-1gb-sgp1-01 python[301478]:     api.check_token(token)
Aug 30 20:57:58 ubuntu-s-1vcpu-1gb-sgp1-01 python[301478]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:57:58 ubuntu-s-1vcpu-1gb-sgp1-01 python[301478]:     raise exceptions.ValidationError(message)
Aug 30 20:57:58 ubuntu-s-1vcpu-1gb-sgp1-01 python[301478]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:58:01 ubuntu-s-1vcpu-1gb-sgp1-01 python[301482]: Traceback (most recent call last):
Aug 30 20:58:01 ubuntu-s-1vcpu-1gb-sgp1-01 python[301482]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:58:01 ubuntu-s-1vcpu-1gb-sgp1-01 python[301482]:     bot = Bot(token=TOKEN)
Aug 30 20:58:01 ubuntu-s-1vcpu-1gb-sgp1-01 python[301482]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:58:01 ubuntu-s-1vcpu-1gb-sgp1-01 python[301482]:     api.check_token(token)
Aug 30 20:58:01 ubuntu-s-1vcpu-1gb-sgp1-01 python[301482]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:58:01 ubuntu-s-1vcpu-1gb-sgp1-01 python[301482]:     raise exceptions.ValidationError(message)
Aug 30 20:58:01 ubuntu-s-1vcpu-1gb-sgp1-01 python[301482]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:58:04 ubuntu-s-1vcpu-1gb-sgp1-01 python[301501]: Traceback (most recent call last):
Aug 30 20:58:04 ubuntu-s-1vcpu-1gb-sgp1-01 python[301501]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 12, in <module>
Aug 30 20:58:04 ubuntu-s-1vcpu-1gb-sgp1-01 python[301501]:     bot = Bot(token=TOKEN)
Aug 30 20:58:04 ubuntu-s-1vcpu-1gb-sgp1-01 python[301501]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 77, in __init__
Aug 30 20:58:04 ubuntu-s-1vcpu-1gb-sgp1-01 python[301501]:     api.check_token(token)
Aug 30 20:58:04 ubuntu-s-1vcpu-1gb-sgp1-01 python[301501]:   File "/home/uaft/uaft_project_50lite/.venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 67, in check_token
Aug 30 20:58:04 ubuntu-s-1vcpu-1gb-sgp1-01 python[301501]:     raise exceptions.ValidationError(message)
Aug 30 20:58:04 ubuntu-s-1vcpu-1gb-sgp1-01 python[301501]: aiogram.utils.exceptions.ValidationError: Token is invalid! It must be 'str' type instead of <class 'NoneType'> type.
Aug 30 20:58:04 ubuntu-s-1vcpu-1gb-sgp1-01 python[301544]: Traceback (most recent call last):
Aug 30 20:58:04 ubuntu-s-1vcpu-1gb-sgp1-01 python[301544]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:58:04 ubuntu-s-1vcpu-1gb-sgp1-01 python[301544]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:58:04 ubuntu-s-1vcpu-1gb-sgp1-01 python[301544]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:58:07 ubuntu-s-1vcpu-1gb-sgp1-01 python[301548]: Traceback (most recent call last):
Aug 30 20:58:07 ubuntu-s-1vcpu-1gb-sgp1-01 python[301548]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:58:07 ubuntu-s-1vcpu-1gb-sgp1-01 python[301548]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:58:07 ubuntu-s-1vcpu-1gb-sgp1-01 python[301548]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:58:09 ubuntu-s-1vcpu-1gb-sgp1-01 python[301549]: Traceback (most recent call last):
Aug 30 20:58:09 ubuntu-s-1vcpu-1gb-sgp1-01 python[301549]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:58:09 ubuntu-s-1vcpu-1gb-sgp1-01 python[301549]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:58:09 ubuntu-s-1vcpu-1gb-sgp1-01 python[301549]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:58:12 ubuntu-s-1vcpu-1gb-sgp1-01 python[301552]: Traceback (most recent call last):
Aug 30 20:58:12 ubuntu-s-1vcpu-1gb-sgp1-01 python[301552]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:58:12 ubuntu-s-1vcpu-1gb-sgp1-01 python[301552]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:58:12 ubuntu-s-1vcpu-1gb-sgp1-01 python[301552]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:58:14 ubuntu-s-1vcpu-1gb-sgp1-01 python[301556]: Traceback (most recent call last):
Aug 30 20:58:14 ubuntu-s-1vcpu-1gb-sgp1-01 python[301556]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:58:14 ubuntu-s-1vcpu-1gb-sgp1-01 python[301556]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:58:14 ubuntu-s-1vcpu-1gb-sgp1-01 python[301556]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:58:17 ubuntu-s-1vcpu-1gb-sgp1-01 python[301560]: Traceback (most recent call last):
Aug 30 20:58:17 ubuntu-s-1vcpu-1gb-sgp1-01 python[301560]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:58:17 ubuntu-s-1vcpu-1gb-sgp1-01 python[301560]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:58:17 ubuntu-s-1vcpu-1gb-sgp1-01 python[301560]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:58:20 ubuntu-s-1vcpu-1gb-sgp1-01 python[301562]: Traceback (most recent call last):
Aug 30 20:58:20 ubuntu-s-1vcpu-1gb-sgp1-01 python[301562]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:58:20 ubuntu-s-1vcpu-1gb-sgp1-01 python[301562]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:58:20 ubuntu-s-1vcpu-1gb-sgp1-01 python[301562]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:58:22 ubuntu-s-1vcpu-1gb-sgp1-01 python[301566]: Traceback (most recent call last):
Aug 30 20:58:22 ubuntu-s-1vcpu-1gb-sgp1-01 python[301566]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:58:22 ubuntu-s-1vcpu-1gb-sgp1-01 python[301566]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:58:22 ubuntu-s-1vcpu-1gb-sgp1-01 python[301566]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:58:25 ubuntu-s-1vcpu-1gb-sgp1-01 python[301567]: Traceback (most recent call last):
Aug 30 20:58:25 ubuntu-s-1vcpu-1gb-sgp1-01 python[301567]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:58:25 ubuntu-s-1vcpu-1gb-sgp1-01 python[301567]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:58:25 ubuntu-s-1vcpu-1gb-sgp1-01 python[301567]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:58:28 ubuntu-s-1vcpu-1gb-sgp1-01 python[301569]: Traceback (most recent call last):
Aug 30 20:58:28 ubuntu-s-1vcpu-1gb-sgp1-01 python[301569]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:58:28 ubuntu-s-1vcpu-1gb-sgp1-01 python[301569]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:58:28 ubuntu-s-1vcpu-1gb-sgp1-01 python[301569]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:58:30 ubuntu-s-1vcpu-1gb-sgp1-01 python[301573]: Traceback (most recent call last):
Aug 30 20:58:30 ubuntu-s-1vcpu-1gb-sgp1-01 python[301573]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:58:30 ubuntu-s-1vcpu-1gb-sgp1-01 python[301573]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:58:30 ubuntu-s-1vcpu-1gb-sgp1-01 python[301573]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:58:33 ubuntu-s-1vcpu-1gb-sgp1-01 python[301577]: Traceback (most recent call last):
Aug 30 20:58:33 ubuntu-s-1vcpu-1gb-sgp1-01 python[301577]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:58:33 ubuntu-s-1vcpu-1gb-sgp1-01 python[301577]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:58:33 ubuntu-s-1vcpu-1gb-sgp1-01 python[301577]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:58:36 ubuntu-s-1vcpu-1gb-sgp1-01 python[301579]: Traceback (most recent call last):
Aug 30 20:58:36 ubuntu-s-1vcpu-1gb-sgp1-01 python[301579]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:58:36 ubuntu-s-1vcpu-1gb-sgp1-01 python[301579]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:58:36 ubuntu-s-1vcpu-1gb-sgp1-01 python[301579]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:58:38 ubuntu-s-1vcpu-1gb-sgp1-01 python[301583]: Traceback (most recent call last):
Aug 30 20:58:38 ubuntu-s-1vcpu-1gb-sgp1-01 python[301583]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:58:38 ubuntu-s-1vcpu-1gb-sgp1-01 python[301583]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:58:38 ubuntu-s-1vcpu-1gb-sgp1-01 python[301583]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:58:41 ubuntu-s-1vcpu-1gb-sgp1-01 python[301586]: Traceback (most recent call last):
Aug 30 20:58:41 ubuntu-s-1vcpu-1gb-sgp1-01 python[301586]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:58:41 ubuntu-s-1vcpu-1gb-sgp1-01 python[301586]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:58:41 ubuntu-s-1vcpu-1gb-sgp1-01 python[301586]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:58:43 ubuntu-s-1vcpu-1gb-sgp1-01 python[301587]: Traceback (most recent call last):
Aug 30 20:58:43 ubuntu-s-1vcpu-1gb-sgp1-01 python[301587]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:58:43 ubuntu-s-1vcpu-1gb-sgp1-01 python[301587]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:58:43 ubuntu-s-1vcpu-1gb-sgp1-01 python[301587]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:58:46 ubuntu-s-1vcpu-1gb-sgp1-01 python[301591]: Traceback (most recent call last):
Aug 30 20:58:46 ubuntu-s-1vcpu-1gb-sgp1-01 python[301591]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:58:46 ubuntu-s-1vcpu-1gb-sgp1-01 python[301591]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:58:46 ubuntu-s-1vcpu-1gb-sgp1-01 python[301591]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:58:48 ubuntu-s-1vcpu-1gb-sgp1-01 python[301597]: Traceback (most recent call last):
Aug 30 20:58:48 ubuntu-s-1vcpu-1gb-sgp1-01 python[301597]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:58:48 ubuntu-s-1vcpu-1gb-sgp1-01 python[301597]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:58:48 ubuntu-s-1vcpu-1gb-sgp1-01 python[301597]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:58:51 ubuntu-s-1vcpu-1gb-sgp1-01 python[301598]: Traceback (most recent call last):
Aug 30 20:58:51 ubuntu-s-1vcpu-1gb-sgp1-01 python[301598]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:58:51 ubuntu-s-1vcpu-1gb-sgp1-01 python[301598]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:58:51 ubuntu-s-1vcpu-1gb-sgp1-01 python[301598]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:58:53 ubuntu-s-1vcpu-1gb-sgp1-01 python[301600]: Traceback (most recent call last):
Aug 30 20:58:53 ubuntu-s-1vcpu-1gb-sgp1-01 python[301600]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:58:53 ubuntu-s-1vcpu-1gb-sgp1-01 python[301600]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:58:53 ubuntu-s-1vcpu-1gb-sgp1-01 python[301600]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:58:56 ubuntu-s-1vcpu-1gb-sgp1-01 python[301603]: Traceback (most recent call last):
Aug 30 20:58:56 ubuntu-s-1vcpu-1gb-sgp1-01 python[301603]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:58:56 ubuntu-s-1vcpu-1gb-sgp1-01 python[301603]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:58:56 ubuntu-s-1vcpu-1gb-sgp1-01 python[301603]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:58:58 ubuntu-s-1vcpu-1gb-sgp1-01 python[301606]: Traceback (most recent call last):
Aug 30 20:58:58 ubuntu-s-1vcpu-1gb-sgp1-01 python[301606]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:58:58 ubuntu-s-1vcpu-1gb-sgp1-01 python[301606]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:58:58 ubuntu-s-1vcpu-1gb-sgp1-01 python[301606]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:59:01 ubuntu-s-1vcpu-1gb-sgp1-01 python[301608]: Traceback (most recent call last):
Aug 30 20:59:01 ubuntu-s-1vcpu-1gb-sgp1-01 python[301608]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:59:01 ubuntu-s-1vcpu-1gb-sgp1-01 python[301608]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:59:01 ubuntu-s-1vcpu-1gb-sgp1-01 python[301608]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:59:04 ubuntu-s-1vcpu-1gb-sgp1-01 python[301615]: Traceback (most recent call last):
Aug 30 20:59:04 ubuntu-s-1vcpu-1gb-sgp1-01 python[301615]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:59:04 ubuntu-s-1vcpu-1gb-sgp1-01 python[301615]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:59:04 ubuntu-s-1vcpu-1gb-sgp1-01 python[301615]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:59:06 ubuntu-s-1vcpu-1gb-sgp1-01 python[301616]: Traceback (most recent call last):
Aug 30 20:59:06 ubuntu-s-1vcpu-1gb-sgp1-01 python[301616]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:59:06 ubuntu-s-1vcpu-1gb-sgp1-01 python[301616]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:59:06 ubuntu-s-1vcpu-1gb-sgp1-01 python[301616]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:59:08 ubuntu-s-1vcpu-1gb-sgp1-01 python[301620]: Traceback (most recent call last):
Aug 30 20:59:08 ubuntu-s-1vcpu-1gb-sgp1-01 python[301620]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:59:08 ubuntu-s-1vcpu-1gb-sgp1-01 python[301620]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:59:08 ubuntu-s-1vcpu-1gb-sgp1-01 python[301620]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:59:11 ubuntu-s-1vcpu-1gb-sgp1-01 python[301623]: Traceback (most recent call last):
Aug 30 20:59:11 ubuntu-s-1vcpu-1gb-sgp1-01 python[301623]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:59:11 ubuntu-s-1vcpu-1gb-sgp1-01 python[301623]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:59:11 ubuntu-s-1vcpu-1gb-sgp1-01 python[301623]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:59:13 ubuntu-s-1vcpu-1gb-sgp1-01 python[301625]: Traceback (most recent call last):
Aug 30 20:59:13 ubuntu-s-1vcpu-1gb-sgp1-01 python[301625]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:59:13 ubuntu-s-1vcpu-1gb-sgp1-01 python[301625]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:59:13 ubuntu-s-1vcpu-1gb-sgp1-01 python[301625]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:59:16 ubuntu-s-1vcpu-1gb-sgp1-01 python[301627]: Traceback (most recent call last):
Aug 30 20:59:16 ubuntu-s-1vcpu-1gb-sgp1-01 python[301627]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:59:16 ubuntu-s-1vcpu-1gb-sgp1-01 python[301627]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:59:16 ubuntu-s-1vcpu-1gb-sgp1-01 python[301627]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:59:18 ubuntu-s-1vcpu-1gb-sgp1-01 python[301631]: Traceback (most recent call last):
Aug 30 20:59:18 ubuntu-s-1vcpu-1gb-sgp1-01 python[301631]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:59:18 ubuntu-s-1vcpu-1gb-sgp1-01 python[301631]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:59:18 ubuntu-s-1vcpu-1gb-sgp1-01 python[301631]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:59:21 ubuntu-s-1vcpu-1gb-sgp1-01 python[301636]: Traceback (most recent call last):
Aug 30 20:59:21 ubuntu-s-1vcpu-1gb-sgp1-01 python[301636]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:59:21 ubuntu-s-1vcpu-1gb-sgp1-01 python[301636]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:59:21 ubuntu-s-1vcpu-1gb-sgp1-01 python[301636]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:59:23 ubuntu-s-1vcpu-1gb-sgp1-01 python[301638]: Traceback (most recent call last):
Aug 30 20:59:23 ubuntu-s-1vcpu-1gb-sgp1-01 python[301638]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:59:23 ubuntu-s-1vcpu-1gb-sgp1-01 python[301638]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:59:23 ubuntu-s-1vcpu-1gb-sgp1-01 python[301638]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:59:26 ubuntu-s-1vcpu-1gb-sgp1-01 python[301642]: Traceback (most recent call last):
Aug 30 20:59:26 ubuntu-s-1vcpu-1gb-sgp1-01 python[301642]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:59:26 ubuntu-s-1vcpu-1gb-sgp1-01 python[301642]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:59:26 ubuntu-s-1vcpu-1gb-sgp1-01 python[301642]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:59:28 ubuntu-s-1vcpu-1gb-sgp1-01 python[301645]: Traceback (most recent call last):
Aug 30 20:59:28 ubuntu-s-1vcpu-1gb-sgp1-01 python[301645]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:59:28 ubuntu-s-1vcpu-1gb-sgp1-01 python[301645]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:59:28 ubuntu-s-1vcpu-1gb-sgp1-01 python[301645]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:59:31 ubuntu-s-1vcpu-1gb-sgp1-01 python[301647]: Traceback (most recent call last):
Aug 30 20:59:31 ubuntu-s-1vcpu-1gb-sgp1-01 python[301647]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:59:31 ubuntu-s-1vcpu-1gb-sgp1-01 python[301647]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:59:31 ubuntu-s-1vcpu-1gb-sgp1-01 python[301647]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:59:34 ubuntu-s-1vcpu-1gb-sgp1-01 python[301653]: Traceback (most recent call last):
Aug 30 20:59:34 ubuntu-s-1vcpu-1gb-sgp1-01 python[301653]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:59:34 ubuntu-s-1vcpu-1gb-sgp1-01 python[301653]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:59:34 ubuntu-s-1vcpu-1gb-sgp1-01 python[301653]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:59:36 ubuntu-s-1vcpu-1gb-sgp1-01 python[301654]: Traceback (most recent call last):
Aug 30 20:59:36 ubuntu-s-1vcpu-1gb-sgp1-01 python[301654]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:59:36 ubuntu-s-1vcpu-1gb-sgp1-01 python[301654]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:59:36 ubuntu-s-1vcpu-1gb-sgp1-01 python[301654]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:59:39 ubuntu-s-1vcpu-1gb-sgp1-01 python[301656]: Traceback (most recent call last):
Aug 30 20:59:39 ubuntu-s-1vcpu-1gb-sgp1-01 python[301656]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:59:39 ubuntu-s-1vcpu-1gb-sgp1-01 python[301656]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:59:39 ubuntu-s-1vcpu-1gb-sgp1-01 python[301656]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:59:41 ubuntu-s-1vcpu-1gb-sgp1-01 python[301659]: Traceback (most recent call last):
Aug 30 20:59:41 ubuntu-s-1vcpu-1gb-sgp1-01 python[301659]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:59:41 ubuntu-s-1vcpu-1gb-sgp1-01 python[301659]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:59:41 ubuntu-s-1vcpu-1gb-sgp1-01 python[301659]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:59:44 ubuntu-s-1vcpu-1gb-sgp1-01 python[301661]: Traceback (most recent call last):
Aug 30 20:59:44 ubuntu-s-1vcpu-1gb-sgp1-01 python[301661]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:59:44 ubuntu-s-1vcpu-1gb-sgp1-01 python[301661]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:59:44 ubuntu-s-1vcpu-1gb-sgp1-01 python[301661]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:59:46 ubuntu-s-1vcpu-1gb-sgp1-01 python[301665]: Traceback (most recent call last):
Aug 30 20:59:46 ubuntu-s-1vcpu-1gb-sgp1-01 python[301665]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:59:46 ubuntu-s-1vcpu-1gb-sgp1-01 python[301665]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:59:46 ubuntu-s-1vcpu-1gb-sgp1-01 python[301665]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:59:49 ubuntu-s-1vcpu-1gb-sgp1-01 python[301670]: Traceback (most recent call last):
Aug 30 20:59:49 ubuntu-s-1vcpu-1gb-sgp1-01 python[301670]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:59:49 ubuntu-s-1vcpu-1gb-sgp1-01 python[301670]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:59:49 ubuntu-s-1vcpu-1gb-sgp1-01 python[301670]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:59:52 ubuntu-s-1vcpu-1gb-sgp1-01 python[301673]: Traceback (most recent call last):
Aug 30 20:59:52 ubuntu-s-1vcpu-1gb-sgp1-01 python[301673]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:59:52 ubuntu-s-1vcpu-1gb-sgp1-01 python[301673]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:59:52 ubuntu-s-1vcpu-1gb-sgp1-01 python[301673]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:59:54 ubuntu-s-1vcpu-1gb-sgp1-01 python[301676]: Traceback (most recent call last):
Aug 30 20:59:54 ubuntu-s-1vcpu-1gb-sgp1-01 python[301676]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:59:54 ubuntu-s-1vcpu-1gb-sgp1-01 python[301676]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:59:54 ubuntu-s-1vcpu-1gb-sgp1-01 python[301676]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:59:57 ubuntu-s-1vcpu-1gb-sgp1-01 python[301680]: Traceback (most recent call last):
Aug 30 20:59:57 ubuntu-s-1vcpu-1gb-sgp1-01 python[301680]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:59:57 ubuntu-s-1vcpu-1gb-sgp1-01 python[301680]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:59:57 ubuntu-s-1vcpu-1gb-sgp1-01 python[301680]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
Aug 30 20:59:59 ubuntu-s-1vcpu-1gb-sgp1-01 python[301681]: Traceback (most recent call last):
Aug 30 20:59:59 ubuntu-s-1vcpu-1gb-sgp1-01 python[301681]:   File "/home/uaft/uaft_project_50lite/tg_runner.py", line 14, in <module>
Aug 30 20:59:59 ubuntu-s-1vcpu-1gb-sgp1-01 python[301681]:     raise RuntimeError("❌ Telegram bot token не найден в окружении (.env)")
Aug 30 20:59:59 ubuntu-s-1vcpu-1gb-sgp1-01 python[301681]: RuntimeError: ❌ Telegram bot token не найден в окружении (.env)
